hashie/hashie

CHANGELOG.md, lib/hashie/dash.rb, spec/hashie/dash_spec.rb
Hello,
When calling `Hashie::Dash.property`, where the `property_name` argument is a string, the method modifies the original value of the argument using the `String#concat` method, appending '=' to the string.
```ruby
klass = Class.new(Hashie::Dash)
my_property_name = 'foo' 
klass.property(my_property_name)
my_property_name
```
I have changed the `Hashie::Dash` code to create a new String object instead of modifying the original.
Thanks!
=> Fix bug where Dash changes argument to `property`

CHANGELOG.md, lib/hashie/dash.rb, spec/hashie/dash_spec.rb
Ability to define defaults based on the current hash. Pretty straight forward.
=> provide self as context when evaluating default

CHANGELOG.md, README.md, lib/hashie.rb, lib/hashie/extensions/deep_find.rb, lib/hashie/extensions/deep_locate.rb, spec/hashie/extensions/deep_locate_spec.rb
Hi everybody, I would like to propose the following extension
```ruby
Hashie::Extensions::DeepLocate
```
It's similar to Hashie::Extensions::DeepFind, but differs in two mayor aspects
* it uses a *comparator callable* instead of a key
* it returns the container enumerables for found elements
I needed this to be able to do modify some complex elasticsearch search requests. These are plain hashes, but the queries can be nested in many ways. One does not know where exactly a certain element might be located. So I wanted to be able to search using some advanced comparator and to modify the results later on in place, which can only be accomplished if the container objects are returned.
**Example**
```ruby
books = [
{
title: "Ruby for beginners",
pages: 120
},
{
title: "CSS for intermediates", …
```
=> Hashie::Extensions::DeepLocate

CHANGELOG.md
The CHANGELOG mistakenly mentions ```Hashie::Extensions::DeepLocate``` for ```3.4.0```, but it was merged after the last release, so it should be ```Next Release```.
=> Remove mention of Hashie::Extensions::DeepLocate for 3.4.0 in changelog

CHANGELOG.md, lib/hashie/extensions/indifferent_access.rb, spec/hashie/extensions/indifferent_access_with_rails_hwia_spec.rb
When using an ActiveRecord::HashWithIndifferentAccess that is nested (i.e. {a: {b: 1}}) to create a Mash with the IndifferentAccess extension, an ArgumentException is raised. This is because the IndifferentAccess method `convert_value` overrides ActiveRecord::HashWithIndifferentAccess's method of the same name. Changing the method name in IndifferentAccess solves the issue.
=> Fix crash building a Mash w/ IndifferentAccess from HashWithIndifferentAccess

.rubocop_todo.yml, CHANGELOG.md, lib/hashie/mash.rb, spec/hashie/mash_spec.rb
Fixes #270. I had to bump Rubocop's max class length. If that's a problem, some refactoring will be necessary.
This will define `reverse_merge` even when ActiveSupport is not included. One solution is to wrap the definition with `if method_defined? :reverse_merge`.
=> Add and test Hashie::Mash#reverse_merge

.travis.yml
Travis released [Docker-based build containers][blog] in December that
should speed up test time. I just had to wait over half an hour for
a build to finish, so I thought we could try this out. I think we're
a pretty ideal candidate because:
1. we don't need sudo for anything; and
2. we aren't an I/O-bound test suite
[blog]: http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
=> Opt in to containerized Travis builds

.travis.yml, spec/hashie/mash_spec.rb
This is a rebased version of the fix by @msievers that makes all of the specs run on Ruby 2.2. I removed 2.2.1 from allowed failures and fixed the merge conflict.
The fix works around an issue in Ruby 2.2 with retrieving methods from `respond_to_missing`.
Original PR: #273 
Ruby language bug tracking: #285 
Reason for adding: #291
=> Fixed specs to run with Ruby 2.2

CHANGELOG.md, README.md, lib/hashie.rb, lib/hashie/extensions/dash/property_translation.rb, lib/hashie/trash.rb
Issue #188 brought up the fact that a Trash is really just a Dash with
some extended behavior. Why don't we make that a little more explicit
and define its behavior as an extension?
*Follow Up*
If this is merged, I move that we deprecate Trash for removal in 4.0.
I think reducing the number of classes will help users better understand
what behavior they are including in their subclasses.
In the long run, a 4.0 release would look really good with all of the behavior
factored out into extension methods. As we continue down that path, we can
slowly deprecate all of the `*ash` classes with the 3.x releases.
What do the other maintainers think of this suggestion?
Fixes #188
=> Extract Trash behavior into an extension

CHANGELOG.md, lib/hashie/extensions/deep_merge.rb, lib/hashie/extensions/stringify_keys.rb, lib/hashie/extensions/symbolize_keys.rb, spec/hashie/extensions/deep_merge_spec.rb, spec/hashie/extensions/stringify_keys_spec.rb, spec/hashie/extensions/symbolize_keys_spec.rb
Fixes issue https://github.com/intridea/hashie/issues/303
=> Fixed #303 (deep_merge/stringify_keys/symbolize_keys not working via hash.extend(…))

CHANGELOG.md, README.md, lib/hashie.rb, lib/hashie/extensions/dash/coercion.rb, spec/hashie/extensions/dash/coercion_spec.rb
Hello!
I need this feature to be able to describe property and its coercion in one line of code.
=> Introduce Hashie::Extensions::Dash::Coercion.

CHANGELOG.md, lib/hashie/extensions/mash/safe_assignment.rb, spec/hashie/extensions/mash/safe_assignment_spec.rb
`Hashie::Extensions::Mash::SafeAssignment` is in trouble!
1. No one should use `methods.include?`, it is **very** slow!
2. There's a trouble with private methods because `methods` doesn't return them.
3. Specs are weak.
=> Speed up SafeAssignment and fix private methods.

CHANGELOG.md, bin/console, bin/setup
A comparison between the current `irb` use case, and the new `bin/console` use case:
Old and janky:
```
∴ irb
>> require "bundler/setup"
=> true
>> require "hashie"
=> true
>> Hashie::Mash.new(hi: "@dblock")
=> #<Hashie::Mash hi="@dblock">
```
New hotness:
```
∴ bin/console
>> Hashie::Mash.new(hi: "@dblock")
=> #<Hashie::Mash hi="@dblock">
```
=> Default bin scripts from bundle gem command: bin/console and bin/setup

CHANGELOG.md, README.md, lib/hashie.rb, lib/hashie/extensions/strict_key_access.rb, spec/hashie/extensions/strict_key_access_spec.rb
In Python a "Hash" is called a "Dictionary", and ...
> "It is an error to extract a value using a non-existent key."
See: https://docs.python.org/2/tutorial/datastructures.html#dictionaries
EXAMPLE:
class StrictHash < Hash
include Hashie::Extensions::Dictionary
end
>> hash = StrictHash[foo: "bar"]
=> {:foo=>"bar"}
>> hash[:foo]
=> "bar"
>> hash[:cow]
KeyError: key not found: :cow
**Why?**  I will be releasing a gem soon which needs this Python dictionary-like requirement.  If not accepted into Hashie, I'll release the dictionary as a separate gem.
=> StrictKeyAccess Extension

CHANGELOG.md, lib/hashie/extensions/deep_locate.rb, spec/hashie/extensions/deep_find_spec.rb, spec/hashie/extensions/deep_locate_spec.rb
`Hashie::Extensions::DeepLocate.deep_locate`, when passed a key, did not
take into account indifferent access. This lead to a regression in
v3.4.1 when `Hashie::Extensions::DeepFind` was modified to be backed by
`DeepLocate`.
This change makes the default comparator aware of indifferent access by
inspecting the object that it is called on. It works with both
`ActiveSupport::HashWithIndifferentAccess` and
`Hashie::Extensions::IndifferentAccess`.
Fixes #309
=> Make DeepLocate indifference-aware by default

CHANGELOG.md, lib/hashie/clash.rb, spec/hashie/clash_spec.rb
Added inheritance
Added multiple bang notation merging
Minor performace improvements - ends_with? is faster than regexp
By @bartoszkopinski, rebased against latest `master`
/cc @dblock
=> Clash: multiple bang notation calls

CHANGELOG.md, UPGRADING.md, lib/hashie/mash.rb, spec/hashie/mash_spec.rb
This one is for discuss. Is this more consistent?
=> Make reverse_merge compatible with subclassing.

CHANGELOG.md, lib/hashie/extensions/indifferent_access.rb, spec/hashie/extensions/indifferent_access_spec.rb
`HashWithDifferentAccess` wasn't properly setting the indifferent
access when merging in other hashes. This reruns `#convert!` after
calling the superclass implementation of the method, so it preserves
indifferent access on the resulting object.
Fixes #345
=> Fix `#merge` breaking indifferent access

.rubocop_todo.yml, CHANGELOG.md, lib/hashie/mash.rb, spec/hashie/mash_spec.rb
In Ruby 2.3.0, I want to use `Hash#dig` with symbol arguments for Mash.
=> Convert Mash keys for #dig

CHANGELOG.md, lib/hashie/extensions/ignore_undeclared.rb, spec/hashie/extensions/ignore_undeclared_spec.rb
Translation from `:symbol` and translation from `'string'` are different translations. No need in coercion to symbol or some other coercions.
=> Stringified translations wasn't working in IgnoreUndeclared.

README.md
The [Coercion Proc sample](https://github.com/intridea/hashie#coercion-proc)'s regular expression is little bit flexible.
I think we should use `/\A ... \z/` regex better than `/^ ... $/`.
The sample will returns `true` if `v` is following.
```
"foo\ntrue\nbaa"
```
=> Update sample of Coercion Proc on README

CHANGELOG.md, lib/hashie/extensions/deep_locate.rb
Hashie's current code assumes that the definition of `ActiveSupport` implies `HashWithIndifferentAccess` has been `require`d at some point. This assumption doesn't necessarily hold in all situations, so I've adjusted the conditional to check for the definition of `ActiveSupport::HashWithIndifferentAccess` explicitly.
I'm unable to create an example within `spec/hashie/extensions/deep_locate_spec.rb` that demonstrates this because `HashWithIndifferentAccess` has already been required. Nor am I aware of how to adjust `require`s within a spec or spec suite to achieve the same effect.
So I've created the following gist which, when run in isolation (`hashie` and `activesupport` gems installed), demonstrates the failure I encountered: …
=> Checking for explicit definition of ActiveSupport::HashWithIndifferentAccess

CHANGELOG.md, lib/hashie/array.rb
Fixes #367
While it's probably not something hashie wants to allow, previously
this was possible so we shouldn't break this when going 3.4.4 to 3.4.5.
As an example, omniauth requires [hashie/mash alone](https://github.com/omniauth/omniauth/blob/d941c4bcb1eb52f3674dd46225808751dd6a1c2f/lib/omniauth/auth_hash.rb#L1)
This appears to have been broken in #358.
Note, we can't write a test for this because we require 'hashie' in the spec_helper
which properly defines the [Hashie::Extensions::Array constant and autoloads
the pretty_inspect here](https://github.com/intridea/hashie/blob/229ee36d7c6a07eff6d8a0434726e12b8c3a0223/lib/hashie.rb#L48)
**Before**
```
10:44:30 ~/Code/hashie (master) (2.3.1) + be irb
irb(main):001:0> require 'hashie/mash'
NameError: uninitialized constant …
```
=> Since hashie/mash can be required alone, require its dependencies

CHANGELOG.md, lib/hashie/extensions/dash/indifferent_access.rb, spec/hashie/extensions/indifferent_access_spec.rb
When using `Hashie::Extensions::Dash::IndifferentAccess` and `Hashie::Extensions::Dash::PropertyTranslation` at the same time, Hashie does not use the translation when accessing properties via `IndifferentAccess`. This modifies `IndifferentAccess` to look for a translation first and use it to access the property.
=> Use existing translations when using IndifferentAccess and IgnoreUndeclared

CHANGELOG.md, lib/hashie/array.rb, spec/hashie/array_spec.rb
I've fixed #373 bug. Issue was caused by trying to convert strings to integers. Default ruby implementation doesn't support it. So my approach is make an attempt to convert string and in case of failure just leave unconverted value to be handled by default #dig method. By doing this we save conversion feature while staying close to original implementation. Made it explicit block to be sure which exception could we catch.
=> Fix dig bug for Array

CHANGELOG.md, lib/hashie.rb, lib/hashie/extensions/ruby_version.rb, lib/hashie/extensions/ruby_version_check.rb, spec/support/ruby_version_check.rb
This is a solution for #375. Moved only required parts of Gem::Version including Copyright. I cant find any significant causes to implement new comparison method.
=> Check ruby version without rubygems

CHANGELOG.md, lib/hashie/extensions/deep_locate.rb, spec/hashie/extensions/deep_find_spec.rb
These changes fix #364 (and #327) issue. Problem appeared in case when current hash has such key. Then deep_locate just pushes this hash into result and doesn't go deeper. After that deep_find fetches value from result hashes by key so only top-level value goes into final result. Still not sure if it should be handled by deep_locate (as in this pr) or deep_find itself should do something smarter.
=> Deep find all goes inside all nested hashes

CHANGELOG.md, UPGRADING.md, lib/hashie/dash.rb, spec/hashie/dash_spec.rb, spec/spec_helper.rb
This change of behaviour fixes at least #362. All procs will be evaluated in object initialization (not only with arity = 1). It makes sense to me because i think that default values should return same values in all possible ways to access them (not only by [] method).
=> Dash default and as json

.rubocop_todo.yml, CHANGELOG.md, README.md, lib/hashie.rb, lib/hashie/mash.rb, lib/hashie/utils.rb, spec/hashie/mash_spec.rb, spec/hashie/utils_spec.rb, spec/hashie_spec.rb, spec/support/logger.rb
One of the most common issues we have reported is when a `Hashie::Mash`
attempts to override a built-in method and fails to do so. To prevent
this from being an issue in the future, I added a logging layer
accessible at `Hashie.logger` that is user-configurable. This should
help to report the error to the user before it becomes a problem.
The logging layer is a barebones implementation right now. It defaults
to a standard `Logger.new($stdout)` but can be overridden by setting
`Hashie.logger = MyAwesomeLogger.new`. Ideally, we can expand this layer
and its usage to make the user experience better for Hashie.
Closes #361
=> Add a logging layer to address common issues

.travis.yml, CHANGELOG.md, Gemfile, spec/spec_helper.rb
CodeClimate > 1.0 uses SimpleCov and requires the test reporter to be
called explicitly:
https://github.com/codeclimate/ruby-test-reporter/blob/master/CHANGELOG.
md#v100-2016-11-03
=> Update to CodeClimate 1.0.x

CHANGELOG.md, hashie.gemspec
Rake 11 has a breaking change (removal of the `#last_comment` method) that doesn't work with our current version of RSpec and Rubocop. Updating RSpec was simple, but we have to update so far in Rubocop that there were a ton of changes that would be required.
This clamps the version of Rake that we use to `< 11`. This should be a temporary fix, but will let us actually have passing builds on Travis again.
=> Fix builds breaking due to Rake 11

.travis.yml
When building master, the usual `bundle exec rake` script has been
replaced with `bundle exec danger`. This works fine in PRs as Danger is
set up to build PRs, but not against master.
This means that tests aren’t actually running for Ruby 2.3.1 in master.
Due to this, code coverage reports aren’t being generated, so the Code
Climate report uploader fails.
Making danger a before_script instead of the main script will enable
the tests to run again when building master.
Fixes the weird side effect from #384. /cc @dblock
=> Move danger to before_script

CHANGELOG.md, lib/hashie/extensions/deep_merge.rb, spec/hashie/extensions/deep_merge_spec.rb
This is a failing test for issue #385 - if you agree with this spec, I can submit a patch to have it `deep_dup` nested hashes before merging to make the test pass.
=> Fix #385 - deep merge by reference bug

.travis.yml, CHANGELOG.md, Gemfile, lib/hashie/extensions/coercion.rb, spec/hashie/extensions/coercion_spec.rb
I'd like to use this gem with Ruby 2.4.0.
I couldn't `bundle install` using Ruby 2.4.0 because activesupport 4.x  is depending old `json` gem.
=> Support Ruby 2.4.0

README.md
Before:
```ruby
class Tweet < Hash
include Hashie::Extensions::Coercion
coerce_key :user, User
end
user_hash = { name: "Bob" }
Tweet.new(user: user_hash)
```
After:
```ruby
class Tweet < Hash
include Hashie::Extensions::Coercion
include Hashie::Extensions::MergeInitializer
coerce_key :user, User
end
user_hash = { name: "Bob" }
Tweet.new(user: user_hash)
#=> {:user=>#<struct User name={:name=>"Bob"}>}
```
Fixes #332
=> Add MergeInitializer to Coercian example

.rspec, CHANGELOG.md, spec/hashie/mash_spec.rb, spec/hashie_spec.rb, spec/support/logger.rb
* Fix for #381: Use of shared context 'with a logger' which caused the example to not be run.
* Fix for #392: Exclude integration specs in rspec (as per exclude pattern in Rakefile)
=> Fix specs for logger warning

.rubocop.yml, CHANGELOG.md, Gemfile, Guardfile, Rakefile, spec/integration/omniauth/integration_spec.rb, spec/support/integration_specs.rb
We have a nice integration spec harness, so let's make sure we use it
when we're working on the gem. I'm making the following changes:
* Make `bundle exec rake` run integration specs, except on Travis.
* Silence a warning in the OmniAuth integration spec that has nothing to
do with Hashie.
* Make Guard run integration specs when appropriate. Now, when you run
all tasks you will run integration specs. Also, if you modify an
integration spec, it will run. Lastly, if you modify anything in `lib`
the integration specs will run.
* Keeps the extra Travis build that only runs integration specs. Travis
didn't like the Rake task that included it and there's extra signal by
doing it this way anyway.
=> Bring integration tests into main test harness

CHANGELOG.md, lib/hashie/mash.rb, spec/hashie/mash_spec.rb
As mentioned in issue #398
I'm not sure making this into one line is acceptable in this project.
RoboCop will complain too many lines for mash.rb if I but it into two lines.
=> Fix passing Pathname object to Hashie::Mesh.load()

.gitignore, CHANGELOG.md, lib/hashie.rb, lib/hashie/logger.rb, spec/integration/rails/.rspec, spec/integration/rails/Gemfile, spec/integration/rails/integration_spec.rb
The auto-load is never triggered because there is no `Hashie::Logger`
constant to trigger it. We need to `require` the file in the top level
`hashie.rb` and anywhere else that uses it (in case someone just loads a
single file).
At the moment, this is only used in Mash, so we're covered.
In addition, try to be smarter about the default logger by setting it to the
Rails logger when we're in a Rails environment.
=> Fix loading of Hashie.logger and set it to Rails.logger when in Rails

.travis.yml, CHANGELOG.md, lib/hashie.rb, lib/hashie/logger.rb, lib/hashie/railtie.rb, spec/integration/omniauth-oauth2/.rspec, spec/integration/omniauth-oauth2/Gemfile, spec/integration/omniauth-oauth2/integration_spec.rb, spec/integration/omniauth-oauth2/some_site.rb, spec/integration/rails/integration_spec.rb
Don't merge this, trying to reproduce #401.
=> Fix #401 w/ integration spec for omniauth-oauth2.

CHANGELOG.md, lib/hashie/railtie.rb, spec/integration/rails-without-dependency/.rspec, spec/integration/rails-without-dependency/Gemfile, spec/integration/rails-without-dependency/integration_spec.rb
In some circumstances when a project has the Rails constant defined we
may still not be able to require the rails/railtie dependency. Before this
change this would raise an exception. This change seeks to add better
detection of the railtie dependency and add logging that this dependency
is missing but still allow execution to continue.
=> Ensure Railties available when loading Railtie

CHANGELOG.md, lib/hashie/mash.rb
By switching to `#respond_to?` we make the lookup of method collisions
a lot faster while retaining the ability to report on them.
Closes #410
=> Fix a performance regression due to logging

CHANGELOG.md, README.md, lib/hashie.rb, lib/hashie/extensions/mash/symbolize_keys.rb, spec/hashie/extensions/mash/symbolize_keys_spec.rb
We often have requests to make Mash symbolize keys by default. Since
Hashie is used across so many different version of Ruby, we have been
hesitant to make this behavior the default. However, there are valid use
cases for wanting symbol keys.
To satisfy both the needs of those on older Rubies and the needs of
those who want symbol keys, this extension gives the end-user the
ability to toggle on symbolized keys in their Mash subclasses. By adding
this ability, we can wait to implement the symbol keys as a default for
a while longer.
See #341, #342 for more information. This is a half-measure toward the
implementation of #342 (which makes Mash symbolize keys by default).
=> Add Hashie::Extensions::Mash::SymbolizeKeys

CHANGELOG.md, lib/hashie/mash.rb, spec/spec_helper.rb
When running rspec specs on the ruby-grape project with warnings enabled
this warning is printed hundreds of times.
This change fixes the warning.
=> Fix "@disable_warnings" spec warning

CHANGELOG.md
Removed _Your contribution here._ in entry for release 3.5.6.
=> Removed boilerplate text from changelog for 3.5.6

CHANGELOG.md, lib/hashie/rash.rb, spec/hashie/rash_spec.rb
[Here](https://github.com/intridea/hashie/blob/32514df06550e21dc47d5c989ff6a90ef0c9b9fa/lib/hashie/rash.rb#L139) it replaces content of the `@regexes` with the new array, based on the count table, which is initially empty and then is filled up with the values after a lookup.
So if there was no lookup for a given regex in 500 lookup cycles, the regex will not get into the table and will be lost after the next optimisation.
=> Fix Hashie::Rash randomly losing keys

CHANGELOG.md, README.md
The behavior of Mash subclasses around the wrapping of inner sub-Hashes can be
confusing, so we should have some documentation around it. This captures the
process of subclasses wrapping their sub-Hashes in a guided fashion.
Also, this reorganizes a bit of the Mash readme to group related topics together
under headlines.
Fixes #432
=> Add documentation for Mash subclasses

CHANGELOG.md, lib/hashie/mash.rb, spec/hashie/mash_spec.rb
In the case where you want to set deeply nested values through chained calls to
the `#[]` method or through method accessors (without using the bang methods),
you might set a `default_proc` on a Mash that recursively creates the key as you
access it. Previously, the `default_proc` was not being propagated down to
sub-Hashes because the way that `#dup` was written wasn't passing the
`default_proc` do the duplicated object.
Now, the `default_proc` is correctly being sent to the duplicated object, which
allows this pattern to work:
```ruby
h = Hashie::Mash.new { |mash, key| mash[key] = mash.class.new(&mash.default_proc) }
h.a.b.c = :xyz
h[:a][:b][:c] #=> :xyz
h[:x][:y][:z] = :abc
h.x.y.z #=> :abc
```
Fixes #208
=> Propagate Mash `default_proc` to sub-Hashes

CHANGELOG.md, lib/hashie/dash.rb, spec/hashie/dash_spec.rb
Definition: Codependent properties
A set of two or more properties who have "required" validations that are based
on each other.
Example:
```ruby
class OneOrMore < Hashie::Dash
property :a, required: -> { b.nil? }
property :b, required: -> { a.nil? }
end
```
When constructing a Dash via the merge initializer, codependent properties have
their "required" validation run too early when their values are set to `nil`,
which causes an `ArgumentError` to be raised in the case that the first property
is set to `nil`.
This is an order-dependence bug that is fixed by this commit. By pruning off
`nil` values only during initialization via the merge initializer, we can
prevent this problem from occurring for the case of `nil` values.
However, this is an indication of a larger problem with the …
=> Allow codependent Dash attributes to initialize

CHANGELOG.md, spec/integration/elasticsearch/Gemfile, spec/integration/elasticsearch/integration_spec.rb
The Elasticsearch gems heavily integrate with Hashie. This leads people to want
to use a Mash as the backer for an Elasticsearch model, but the behavior is
different than they expect. By having this integration spec, we're covering two
things:
1. It might help ensure that we don't break the Elasticsearch ecosystem with
changes in Hashie as has happened in the past.
2. It communicates some gotchas that happen with using a Mash as the backer for
an Elasticsearch model.
Resolves #354
=> Add an integration spec for Elasticsearch

CHANGELOG.md, lib/hashie/extensions/parsers/yaml_erb_parser.rb
`Hashie::Mash.load` require `Pathname` since v3.4.5.
see: bbafaded9d
```
irb(main):001:0> require "hashie"
=> true
irb(main):002:0> Hashie::Mash.load("foo.yml")
Traceback (most recent call last):
6: from /opt/rubies/2.6.0-dev/bin/irb:11:in `<main>'
5: from (irb):2
4: from /Users/onaka/.gem/ruby/2.6.0/gems/hashie-3.5.7/lib/hashie/mash.rb:105:in `load'
3: from /Users/onaka/.gem/ruby/2.6.0/gems/hashie-3.5.7/lib/hashie/extensions/parsers/yaml_erb_parser.rb:19:in `perform'
2: from /Users/onaka/.gem/ruby/2.6.0/gems/hashie-3.5.7/lib/hashie/extensions/parsers/yaml_erb_parser.rb:19:in `new'
1: from /Users/onaka/.gem/ruby/2.6.0/gems/hashie-3.5.7/lib/hashie/extensions/parsers/yaml_erb_parser.rb:9:in `initialize'
NameError (uninitialized constant Hashie::Extensions::Parsers::YamlErbParser::Pathname) …
```
=> Fix: NameError (uninitialized constant Hashie::Extensions::Parsers::YamlErbParser::Pathname)

lib/hashie/extensions/coercion.rb
Unless  `<=` operator is overwritten (which, unless we have missed something, is not), to check if the type class is a Hash, it is more readable to use `==` than `<=`. It returns `false`/`true` instead of `nil`/`0`, but this doesn't make a different when using it in a condition. :bowtie: 
As the code is now self-explanatory, the comment can be removed. :wink: 
Co-authored-by: Ana María Martínez Gómez <ammartinez@suse.de>
=>  Use == instead of <= in build_coercion 

CHANGELOG.md, lib/hashie/mash.rb, spec/hashie/mash_spec.rb
Addresses: https://github.com/intridea/hashie/issues/464
Checks if key is present in `deep_update` before calling any reader method. Calling a reader method will execute the default block and we now prevent it.
=> Calls readers only when a key exists for Mash#update

.rubocop_todo.yml, CHANGELOG.md, README.md, lib/hashie.rb, lib/hashie/extensions/mash/define_accessors.rb, lib/hashie/mash.rb, spec/hashie/extensions/mash/define_accessors_spec.rb
This patch adds an extension for Mash that makes it behave like `OpenStruct`. It reduces overhead of `method_missing?` magic which is a good thing! It's inspired by the recent @sferik's work on `OpenStruct` — https://github.com/ruby/ruby/pull/1033.
When using it in `Mash` subclasses it makes them _remember_ methods so then it's more like `ActiveModel` than `OpenStruct` in this case.
To use it like `OpenStruct` one could use this shortcut:
``` ruby
{ foo: 1, bar: 2 }.to_mash.with_accessors!
```
Implementation details:
It injects to class an anonymous module that stores accessor method definitions. This is inspired by `ActiveModel` / `ActiveRecord`. It allows to override accessors in subclass and call them via `super` if this is intended.
=> Add Hashie::Extensions::Mash::DefineAccessors.

.rubocop.yml, .rubocop_todo.yml, Gemfile, lib/hashie/dash.rb, lib/hashie/extensions/coercion.rb, lib/hashie/extensions/dash/property_translation.rb, lib/hashie/extensions/deep_fetch.rb, lib/hashie/extensions/deep_find.rb, lib/hashie/extensions/deep_locate.rb, lib/hashie/extensions/mash/keep_original_keys.rb, lib/hashie/extensions/method_access.rb, lib/hashie/extensions/strict_key_access.rb, lib/hashie/rash.rb, spec/hashie/dash_spec.rb, spec/hashie/extensions/coercion_spec.rb, spec/hashie/extensions/deep_find_spec.rb, spec/hashie/extensions/deep_locate_spec.rb, spec/hashie/extensions/deep_merge_spec.rb, spec/hashie/hash_spec.rb, spec/hashie/mash_spec.rb, spec/hashie/trash_spec.rb, spec/integration/elasticsearch/integration_spec.rb, spec/integration/rails/integration_spec.rb
For accessibility reasons, we should limit our lines to 100 chars max.
https://github.com/slack-ruby/slack-ruby-client/pull/293#discussion_r309472083
We could go more aggressive on this, but not sure if we should.
=> Change rubocop to restrict to 100 character lines.

README.md, UPGRADING.md, lib/hashie/extensions/key_conflict_warning.rb, lib/hashie/extensions/parsers/yaml_erb_parser.rb, lib/hashie/mash.rb, spec/hashie/mash_spec.rb
Self explanatory, the whitelist changes in particular match what Ruby 2.6+ refer to them as.
It looks like Ruby 2.6 wants those params passed in as keyword args, but that's a task for another PR.
=> Remove references to blacklists and whitelists

README.md
We had some broken shields and things in the readme due to moving the repository. This updates all those references to the new location.
[ci skip]
=> Update the README from moving the repo

CHANGELOG.md, CONTRIBUTING.md, Gemfile, bin/setup, hashie.gemspec
RubyGems.org has recently added the capability to have extra metadata
URLs shown on the gem page. These are handy for people who are new to a
gem or need to report an issue.
When you're installing a gem in a production environment, you want it to
install as fast it can. One of the ways you can speed up the
installation of the gem is by making it smaller. We currently ship the
test suite with the gem, increasing the size of the built gem
significantly.
By not shipping the test suite, we can shrink the size of the gem by
38%. Below are the measurements I took for that statement.
**The size of the gem with the test suite**
$ du -b hashie-4.0.1.gem
80384	hashie-4.0.1.gem
**The size of the gem without the test suite**
$ du -b hashie-4.0.1.gem
50176	hashie-4.0.1.gem
Our contributing …
=> Update the gemspec for improved information and installation size/speed

CHANGELOG.md, lib/hashie/extensions/deep_merge.rb, lib/hashie/utils.rb, spec/hashie/extensions/deep_merge_spec.rb
The `DeepMerge` extension has two methods of mutating hashes: a
destructive one and a non-destructive one. The `#deep_merge` version
should not mutate the original hash or any hash nested within it. The
`#deep_merge!` version is free to mutate the receiver.
Without deeply duplicating the values contained within the hash, the
invariant of immutability cannot be held for the original hash. In order
to preserve that invariant, we need to introduce a method of deeply
duplicating the hash.
The trick here is that we cannot rely on a simple call to `Object#dup`.
Some classes within the Ruby standard library are not duplicable in
particular versions of Ruby. Newer versions of Ruby allow these classes
to be "duplicated" in a way that returns the original value. These
classes represent value …
=> Prevent deep_merge from mutating nested hashes

CHANGELOG.md, Gemfile, README.md, benchmarks/permissive_respond_to.rb, lib/hashie.rb, lib/hashie/extensions/mash/permissive_respond_to.rb, spec/hashie/extensions/mash/permissive_respond_to_spec.rb
By default, Mashes don't state that they respond to unset keys. This
causes unexpected behavior when you try to use a Mash with a
SimpleDelegator.
This new extension allows you create a permissive subclass of Mash that
will be fully compatible with SimpleDelegator and allow you to fully do
thunk-oriented programming with Mashes.
This comes with the trade-off of a ~19KB cache for each of these
subclasses and a ~20% performance penalty on any of those subclasses.
Closes #461
=> Add a PermissiveRespondTo extension for Mashes

CHANGELOG.md, lib/hashie/mash.rb, spec/hashie/mash_spec.rb
In order for `#dig` to work properly, we need Arrays to be
`Hashie::Array`s to be aware of the key conversion. Our original
`Mash#convert_value` method was deconverting `Hashie::Array`s into
normal Arrays and causing `#dig` to behave in an unexpected manner.
Fixes #504
=> Ensure that Hashie::Arrays are not deconverted

CHANGELOG.md, lib/hashie/extensions/parsers/yaml_erb_parser.rb
This PR suppresses the following `Psych.safe_load` args warn when using Psych 3.1.0 (Ruby 2.6+).
```console
% bundle exec rake spec
(snip)
/Users/koic/src/github.com/intridea/hashie/lib/hashie/extensions/parsers/yaml_erb_parser.rb:22:
Passing permitted_classes with the 2nd argument of Psych.safe_load is
deprecated. Use keyword argument like Psych.safe_load(yaml,
permitted_classes: ...) instead.
/Users/koic/src/github.com/intridea/hashie/lib/hashie/extensions/parsers/yaml_erb_parser.rb:22:
Passing permitted_symbols with the 3rd argument of Psych.safe_load is
deprecated. Use keyword argument like Psych.safe_load(yaml,
permitted_symbols: ...) instead.
/Users/koic/src/github.com/intridea/hashie/lib/hashie/extensions/parsers/yaml_erb_parser.rb:22:
Passing aliases with the 4th argument of …
```
=> Suppress `Psych.safe_load` arg warn when using Psych 3.1.0+

CHANGELOG.md, lib/hashie/mash.rb, spec/hashie/mash_spec.rb
Another issue I came across while working on #508. It wasn't caught before because we included activesupport in the test suite and therefore `#compact` was monkey patched in.
=> Only define compact on ruby >= 2.4

CHANGELOG.md, lib/hashie/mash.rb, spec/hashie/mash_spec.rb, spec/spec_helper.rb, spec/support/matchers.rb
Due to how we have implemented the bang/underbang/query behavior within
Mash, setting keys that have those affixes in them actually allow
overwriting the behavior of those affixes. As such, we shouldn't warn
when setting a key that matches those patterns.
When it comes to setter-like keys, I believe we still _do_ want to warn
for two reasons:
1. Trying to access the key via method access is a syntax error. Ruby
expects any method ending in `=` to be a 2+-arity method due to the
infix notation of setter methods. This is unexpected behavior unless
you're very familiar with Ruby parsing.
2. You can still retrieve the key via the normal `Hash#[]` reader, but
it prevents setting a similar key without the equal sign. You can see
this in the test about setters. I'd say that is unexpected and …
=> Don't warn when setting most affixed keys

CHANGELOG.md, spec/hashie/extensions/mash/symbolize_keys_spec.rb
This PR suppresses the following keyword arguments warning for Ruby 2.7.0.
```console
% bundle exec rspec spec/hashie/extensions/mash/symbolize_keys_spec.rb
(snip)
/Users/koic/src/github.com/hahie/hashie/spec/hashie/extensions/mash/symbolize_keys_spec.rb:29:
warning: Using the last argument as keyword parameters is
deprecated; maybe ** should be added to the call
/Users/koic/src/github.com/hahie/hashie/spec/hashie/extensions/mash/symbolize_keys_spec.rb:21:
warning: The called method `call' is defined here
```
For Ruby 2.8.0-dev (Ruby 3.0) the warning will be `ArgumentError`.
ruby/ruby#2794
=> Suppress keyword arguments warning for Ruby 2.7.0

CHANGELOG.md, README.md, lib/hashie/extensions/dash/property_translation.rb, lib/hashie/utils.rb
This PR suppresss the following integer unification warning for using Ruby 2.4.0+
```console
% ruby -v
ruby 2.4.9p362 (2019-10-02 revision 67824) [x86_64-darwin17]
% bundle exec rspec spec/hashie/extensions/deep_merge_spec.rb
Hashie::Extensions::DeepMerge
/Users/koic/src/github.com/hahie/hashie/lib/hashie/utils.rb:38: warning:
constant ::Fixnum is deprecated
/Users/koic/src/github.com/hahie/hashie/lib/hashie/utils.rb:38: warning:
constant ::Bignum is deprecated
```
This PR makes the following change to the product code:
```diff
diff --git a/lib/hashie/utils.rb b/lib/hashie/utils.rb
index 5b55b9a..a1365f8 100644
--- a/lib/hashie/utils.rb
+++ b/lib/hashie/utils.rb
@@ -21,24 +21,11 @@ module Hashie
def self.safe_dup(value)
case value
-      when Complex, FalseClass, NilClass, Rational, …
```
=> Suppress an integer unification warning for Ruby 2.4.0+

CHANGELOG.md, lib/hashie/extensions/ruby_version_check.rb, lib/hashie/mash.rb
This PR suppresses the following warning that `deep_merge` method and `deep_update` method are defined twice when using Ruby 2.6.0+.
```console
% bundle exec rake
(snip)
/Users/koic/src/github.com/hahie/hashie/lib/hashie/mash.rb:226: warning:
method redefined; discarding old deep_merge
/Users/koic/src/github.com/hahie/hashie/lib/hashie/mash.rb:212: warning:
previous definition of deep_merge was here
/Users/koic/src/github.com/hahie/hashie/lib/hashie/mash.rb:232: warning:
method redefined; discarding old deep_update
/Users/koic/src/github.com/hahie/hashie/lib/hashie/mash.rb:218: warning:
previous definition of deep_update was here
```
=> Suppress a Ruby's warning when using Ruby 2.6.0+

spec/integration/elasticsearch/integration_spec.rb
Here is the implementation of index_document in elasticseach-model gem,
```
def index_document(options={})
document = as_indexed_json
request = { index: index_name,
id:    id,
body:  document }
request.merge!(type: document_type) if document_type
client.index(request.merge!(options))
end 
```
This spec is failing because the as_indexed_json method returns nil, resulting in body key to nil, which should not be.
To fix this spec, I have implemented the as_indexed_json method in MyModel class, but I am not sure whether this is the correct way. 
pr #518
@dblock @michaelherold
=> Elasticsearch integration spec fix

CHANGELOG.md, README.md, UPGRADING.md, lib/hashie/extensions/mash/symbolize_keys.rb, lib/hashie/extensions/symbolize_keys.rb, lib/hashie/hash.rb, lib/hashie/mash.rb, lib/hashie/version.rb, spec/hashie/extensions/mash/symbolize_keys_spec.rb, spec/hashie/extensions/symbolize_keys_spec.rb, spec/hashie/hash_spec.rb, spec/hashie/mash_spec.rb
As `Mash` is conceived to provide psuedo-object functionality, handling keys which cannot represent a method call falls outside the scope of provided value.
This PR changes the initialization behavior of `Mash` to convert keys to strings _only when the key is a candidate for indifferent (string/symbol) access_. That is, non-string/symbol keys such as `1`, `["1"]` `{foo: "bar"}` will be left as is.
Before this PR, we would see:
```rb
[1] pry(main)> Hashie::Mash.new({foo: "bar"} => "baz", "1" => "one string", :"1" => "one sym", 1 => "one num")
=> {"{:foo=>\"bar\"}"=>"baz", "1"=>"one num"}
```
After this PR, we see:
```rb
[1] pry(main)> Hashie::Mash.new({foo: "bar"} => "baz", "1" => "one string", :"1" => "one sym", 1 => "one num")
=> {{:foo=>"bar"}=>"baz", "1"=>"one sym", 1=>"one num"}
``` …
=> Changes to `Mash` initialization key string conversion.

.travis.yml, CHANGELOG.md, Dangerfile, Gemfile, README.md
Added TOC and upgraded danger-changelog to verify the keep-a-changelog formatted CHANGELOG. Note that the "Miscellaneous" section is not a thing in that format and that I had to fix https://github.com/dblock/danger-changelog/pull/58.
=> Added TOC and upgraded danger-changelog to verify the keep-a-changelog formatted CHANGELOG.

.travis.yml, CHANGELOG.md
`sudo: false` is deprecated.
https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
=> Test with Ruby 2.7

CHANGELOG.md, LICENSE, README.md
Closes https://github.com/hashie/hashie/issues/495
=> Updated Copyright to 2020.

CHANGELOG.md, README.md, lib/hashie.rb, lib/hashie/extensions/dash/predefined_values.rb, spec/hashie/extensions/dash/predefined_values_spec.rb
Extends a Dash with the ability to accept only predefined values on a property.
#61
=> Hashie::Extensions::Dash::PredefinedValues

CHANGELOG.md, README.md, lib/hashie/extensions/indifferent_access.rb, spec/hashie/extensions/indifferent_access_spec.rb
Following the conventions in `activesupport` and the semantics of the
`#to_hash` method in Ruby's standard library, the `#to_hash` method for
a hash that has mixed in `IndifferentAccess` will now export the hash as
a normal, not-indifferent hash.
Closes #452
=> Allow exporting a normal, not-indifferent Hash

.travis.yml, CHANGELOG.md
Support for Ruby 2.4 was [dropped in April of this year][1], with other
versions earlier than that.
Per the [JRuby security policy][2], JRuby 9.2 is supported, but 9.0 is
not any longer.
JRuby 9.0 has been flaky on builds, so it's now causing a maintenance
burden.
This isn't a declaration that we won't support these versions, but I
don't think it makes sense to test on them any more. In the next major
release, I would like to define a support policy.
[1]: https://www.ruby-lang.org/en/news/2020/04/05/support-of-ruby-2-4-has-ended/
[2]: https://github.com/jruby/jruby/blob/4fd5e619f9d1f36d7bbca8f0013bb55e4ad57e8f/SECURITY.md
=> Drop testing for JRuby 9.0

.travis.yml, CHANGELOG.md
Was using this projects Travis CI configuration as a reference on how one could execute the CodeClimate job and noticed that the tests for Ruby 2.7 were executed twice.
This change leaves the responsibility for testing 2.7 to the Danger+CodeClimate job.
=> Run 2.7 tests once

CHANGELOG.md, README.md, lib/hashie/dash.rb, lib/hashie/extensions/ignore_undeclared.rb, spec/hashie/dash_spec.rb, spec/hashie/extensions/ignore_undeclared_spec.rb, spec/spec_helper.rb, spec/support/shared_examples.rb
The normal behavior of Dash with respect to property defaults differed
from the behavior of a Dash/Trash with IgnoreUndeclared mixed in. This
is because some situations called the defaults and some did not.
This change normalizes the behavior so that all situations where the
defaults should be used to override unset values behave consistently,
as well as all situations where the default should not override a `nil`
value.
Closes #471
=> Fix inconsistencies with Dash defaults

lib/hashie/mash.rb
Because `Hashie::Mash`'s parent class `Hashie::Hash` already includes this very module `Hashie::Extensions::PrettyInspect`. https://github.com/hashie/hashie/blob/75410a6/lib/hashie/hash.rb#L9
=> No need to include Hashie::Extensions::PrettyInspect into Hashie::Mash

.github/workflows/main.yml
Danger can't find the commit in the PR because it's missing a token (?).
```
RuntimeError: Commit 9ba96e03 doesn't exist. Are you running `danger local/pr` against the correct repository? Also this usually happens when you rebase/reset and force-pushed.
/home/runner/work/hashie/hashie/vendor/bundle/ruby/2.7.0/gems/danger-8.4.1/lib/danger/scm_source/git_repo.rb:117:in `raise_if_we_cannot_find_the_commit'
/home/runner/work/hashie/hashie/vendor/bundle/ruby/2.7.0/gems/danger-8.4.1/lib/danger/scm_source/git_repo.rb:99:in `ensure_commitish_exists_on_branch!'
/home/runner/work/hashie/hashie/vendor/bundle/ruby/2.7.0/gems/danger-8.4.1/lib/danger/request_sources/github/github.rb:116:in `setup_danger_branches'
/home/runner/work/hashie/hashie/vendor/bundle/ruby/2.7.0/gems/danger-8.4.1/lib/danger/dange …
```
=> Fix: use a personal danger token.

CHANGELOG.md, lib/hashie/extensions/indifferent_access.rb, lib/hashie/mash.rb, spec/hashie/extensions/indifferent_access_spec.rb, spec/hashie/mash_spec.rb
Ruby 3 adds the Hash#except method, which should return the correct Hashie object instance when called on a Mash or object using the Hashie::Extensions::IndifferentAccess mixin.
This change implements `#except` in both of those locations and adds the corresponding specs.
=> Add #except under Ruby 3

CHANGELOG.md, lib/hashie/dash.rb, lib/hashie/extensions/dash/indifferent_access.rb, lib/hashie/extensions/indifferent_access.rb, spec/hashie/dash_spec.rb
Merging https://github.com/hashie/hashie/pull/535
=> Michaelherold dash nil keys

CHANGELOG.md, lib/hashie/dash.rb, lib/hashie/extensions/dash/indifferent_access.rb, lib/hashie/extensions/indifferent_access.rb, spec/hashie/dash_spec.rb
In #437, we added the ability to have nilable codependent attributes. However, this change introduced a regression where those codependent attributes are no longer exported because they are not stored internally.
This change adds exporting for all Dash properties, whether they are set or not. The behavior uses the default value as the export for a key that was missing during initialization. If you set the value to `nil` later, it will be `nil` in the export.
Note that there is behavior in here that is related to an implementation detail of MRI (and currently JRuby) as noted in the last commit and in the comment above two example groups in the specs. I wanted to explicitly document it because it's not commonly known behavior.
Lastly, this includes a small refactor of how …
=> Export all Dash properties with their defaults, even when not set internally

README.md
This was added in https://github.com/hashie/hashie/pull/34/commits/d20eed6540b7cc264583244088344f73436292b7 but was never documented.
=> Include example of Dash's lazy evaluation feature

.github/workflows/main.yml, .rubocop.yml, CHANGELOG.md, Gemfile, Guardfile, Rakefile, bin/console, hashie.gemspec, lib/hashie/extensions/coercion.rb, lib/hashie/mash.rb, lib/hashie/version.rb, spec/hashie/array_spec.rb, spec/hashie/extensions/coercion_spec.rb, spec/hashie/mash_spec.rb, spec/integration/omniauth/Rakefile, spec/support/integration_specs.rb
In addition to adding Ruby 3.1 to the CI configuration a number of other changes were required to get everything to pass.  This included:
- Updating Rubocop to ~> 1.0 for Rubies 2.4 and greater
- Disabling the Rubocop run in rake for Rubies before Ruby 2.4
- Quoting '3.0' in the CI configuration to ensure it loads a 3.0.x Ruby
- Set RUBYOPT="--disable_error_highlight" so Ruby 3.1 error matchers pass (both in CI configuration and in integration spec command)
- Fixing a few trivial lints
=> Add Ruby 3.1 to CI

.github/workflows/danger.yml, .github/workflows/test.yml, CHANGELOG.md, spec/hashie/mash_spec.rb, spec/hashie/utils_spec.rb
Getting Ruby 3.2 to green required a few minor changes to the specs:
1. Since `trust` is no longer a method on `Object` in Ruby 3.2, another built-in method needed to be used instead.  I chose `object_id` and updated references accordingly.
2. One spec depended on the behavior of Psych when aliases are not supported.  That behavior changed in Psych 5, and a different exception is raised.  I updated the code to check the Psych version and run the appropriate test.
This runs green on my fork.
=> Add Ruby 3.2 to the CI matrix

spec/integration/omniauth/Rakefile, spec/integration/omniauth/app.rb
```
1) omniauth works
Failure/Error: get '/'
ArgumentError:
invalid secret: 24, must be >=64
```
https://github.com/hashie/hashie/actions/runs/8597426729/job/23574774172
Rails secret min length has changed in a minor version?
=> Fix: integration tests in CI.
